# -- FILE: .travis.yml
language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1

install:
  - pip install tox-travis
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls