# Config file for automatic testing at travis-ci.org
language: python

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox

# command to run tests using coverage, e.g. python setup.py test
script: tox

# report coverage to coveralls.io
after_success: coveralls
